Home_page:
    path:     /
    defaults:
        _controller:  OPPlatformBundle:Advert:index
        page: 1
    requirements:
        page: \d*

View_page:
    path:     /advert/{id}
    defaults:
        _controller:  OPPlatformBundle:Advert:view
        page:         1
    requirements:
        id: \d+

Add_page:
    path:     /add
    defaults:
        _controller:  OPPlatformBundle:Advert:add

Edit_page:
    path:     /edit/{id}
    defaults:
        _controller:  OPPlatformBundle:Advert:edit
    requirements:
        id: \d+

Delete_page:
    path:     /delete/{id}
    defaults:
        _controller:  OPPlatformBundle:Advert:delete
    requirements:
        id: \d+