<?php

namespace OP\UserBundle;

use Symfony\Component\HttpKernel\Bundle\Bundle;

class OPUserBundle extends Bundle
{
    public function getParent()
    {
        return 'FOSUserBundle'; // TODO: Change the autogenerated stub
    }
}
